// <auto-generated />
using System;
using ForgeInsole.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForgeInsole.Data.Migrations
{
    [DbContext(typeof(ForgeInsoleDbContext))]
    partial class ForgeInsoleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForgeInsole.Data.Entities.Insole", b =>
                {
                    b.Property<string>("InsoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firmware")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("InsoleId");

                    b.ToTable("Insoles");

                    b.HasData(
                        new
                        {
                            InsoleId = "forge-insole-01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Firmware = "1.4.0",
                            Label = "Forge Insole 01",
                            Side = "L",
                            Source = "Simulated",
                            Status = "Active"
                        },
                        new
                        {
                            InsoleId = "forge-insole-02",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Firmware = "1.4.0",
                            Label = "Forge Insole 02",
                            Side = "R",
                            Source = "Simulated",
                            Status = "Active"
                        },
                        new
                        {
                            InsoleId = "forge-insole-03",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Firmware = "1.4.0",
                            Label = "Forge Insole 03",
                            Side = "L",
                            Source = "Simulated",
                            Status = "Active"
                        },
                        new
                        {
                            InsoleId = "forge-insole-04",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Firmware = "1.4.0",
                            Label = "Forge Insole 04",
                            Side = "R",
                            Source = "Simulated",
                            Status = "Active"
                        },
                        new
                        {
                            InsoleId = "forge-insole-05",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Firmware = "1.3.2",
                            Label = "Forge Insole 05",
                            Side = "L",
                            Source = "Simulated",
                            Status = "Active"
                        },
                        new
                        {
                            InsoleId = "forge-insole-06",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Firmware = "1.3.2",
                            Label = "Forge Insole 06",
                            Side = "R",
                            Source = "Simulated",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ForgeInsole.Data.Entities.SimulationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("SimulationSessions");
                });

            modelBuilder.Entity("ForgeInsole.Data.Entities.TelemetryReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AccelX")
                        .HasColumnType("float");

                    b.Property<double>("AccelY")
                        .HasColumnType("float");

                    b.Property<double>("AccelZ")
                        .HasColumnType("float");

                    b.Property<double>("Cadence")
                        .HasColumnType("float");

                    b.Property<double>("ContactTimeMs")
                        .HasColumnType("float");

                    b.Property<string>("FootStrike")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GaitBalance")
                        .HasColumnType("float");

                    b.Property<double>("GyroX")
                        .HasColumnType("float");

                    b.Property<double>("GyroY")
                        .HasColumnType("float");

                    b.Property<double>("GyroZ")
                        .HasColumnType("float");

                    b.Property<double>("ImpactForce")
                        .HasColumnType("float");

                    b.Property<string>("InsoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("PressureForefoot")
                        .HasColumnType("float");

                    b.Property<double>("PressureHeel")
                        .HasColumnType("float");

                    b.Property<double>("PressureMidfoot")
                        .HasColumnType("float");

                    b.Property<Guid?>("SimulationSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Steps")
                        .HasColumnType("int");

                    b.Property<double>("StrideAsymmetryPct")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InsoleId", "Timestamp");

                    b.ToTable("TelemetryReadings");
                });

            modelBuilder.Entity("ForgeInsole.Data.Entities.TelemetryReading", b =>
                {
                    b.HasOne("ForgeInsole.Data.Entities.Insole", null)
                        .WithMany()
                        .HasForeignKey("InsoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
