namespace ForgeInsole.Data.Entities
{
    // Groups the readings generated by one continuous run of the background generator.
    public class SimulationSession
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public DateTime StartedAt { get; set; } = DateTime.UtcNow;
        public DateTime? EndedAt { get; set; }
    }
}
